// THIS FILE IS AUTOMATICALLY GENERATED IN HERE:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import SafaGridView from './SafaGridView.vue'

// Export components individually
export { SafaGridView }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('SafaGridView', SafaGridView)
}

// Export the library as a plugin
export default { install: install }
